### ISSUE TITLE
Andrew Lee Boss Art

### ISSUE THREAD

**Issue by goofanader** [goofanader/minna-no-fighting-game#13]
### Andrew Lee
- [x] Front Facing Sprite
- [x] Idle Frame
- [x] Point to the Right Frame (but it's an open palm, not a point lol)
- [x] Force Blast Sprite (is actually the Point to the Right Frame)
### Rika (Optional)
- [ ] Come out from the side of the screen Movement
  For the attacks, she needs a setup into the attack animation.
- [ ] Attack 1 Animation: a scythe cross slash attack for close range
- [ ] Attack 2 Animation: crystals that shoot projectiles
- [ ] Force Blast Animation: When Andrew calls a force blast, Rika comes out and spins her scythe around Andrew, knocking back players
- [ ] Leave the Screen Movement
  Phyllis: I keep imagining her leaping from the ground and out of the top corner of the screen, back towards the direction that Andrew is at.
### Special Attack
- [x] JPEG artifacted all images
## References
- **Boss Name:** Omega Andrew Lee
- **References:**
  - [Andrew Lee Reference (he's on the left)](https://drive.google.com/open?id=0BzV7wJdvnkrrRkNqWFFmOF9FS3M)
  - [Andrew Lee's "Animation" Style](https://www.youtube.com/watch?v=30DyYkoNH9Q)
  - [Rika/Attack 1 Reference](https://drive.google.com/open?id=0BzV7wJdvnkrrazB3YlJTMXcyc3M)
  - [Special Attack's Style](https://youtu.be/yw2SKh28bMQ?t=76)
  - [Files of Additional Characters for Special](https://drive.google.com/open?id=0BzV7wJdvnkrrY1VPWkhreWZyX1U)
- **Opening Monologue:** I'LL KIL- What was the ESRB rating on this game again? I'LL DESTROY Y- Oh, it isn't going to be rated? I WILL OWN THE SHI-
  
  The dialogue should be cut off via the dialogue box. (The monologue has been changed from what it was originally to keep it shorter)
## Additional Items/Changes to the Reference

You probably have a picture of me, but go off of "generic clean shaved Asian male with glasses". I'd like it to be as "generic" as possible in that respect.
- **Legs/Pants:** off-white pants
- **Feet/Shoes:** black shoes
## Colors
- **Primary:** black
- **Secondary:** off-white
- **Tertiary:** none
### Regular Attack: Furude Rika

I "send" her out like those assist moves in fighters, where they come from offscreen behind me. She has 2 attacks, a scythe cross slash attack for close range, and her crystals that shoot projectiles.
### Special Attack: Miyuki Sawashiro

Various stills of all of Miyuki Sawashiro's voiced characters come from off screen with a trailing light aura and does damage on hit. A different character comes from each side/section of the screen. If we're doing a standard widescreen game I guess that would be 3 characters from top, 1 left, 1 right, and 3 bottom for a total of 8. Ideally, the attack should be as close to full screen as possible after all the characters have hit. Not sure if you're doing one of the "Screen Freeze" things when they do a special, but I'd like to announce the attack in that respect.

Her attack is based on Omega Tom Hanks: https://youtu.be/yw2SKh28bMQ?t=76
## Animation

I have basically 2 stills, that may sort of do that floating thing that FF bosses used to do.

Animation should be like Culex from Super Mario RPG with the lazy animation - that's what I'm going for: https://www.youtube.com/watch?v=30DyYkoNH9Q
### Idle

Standing idly. Just one frame
### Send Out Attack

It's like the Phoenix Wright hold it thing when I send out an attack but an open hand? (make sure it looks like an open hand else it could be misinterpreted badly). 1 frame
## Phyllis Notes

We're not doing Rika unless we have time. Sorry, Andrew :(

**Comment by goofanader** [comment]
I shortened the opening monologue.

**Comment by goofanader** [comment]
Edited Rika's checkbox information since I didn't read Andrew Lee's description of her well. I thought she was another character entirely, not a support character lol

Also, changed the force blast to be another attack that Andrew calls Rika for.

**Comment by ghost** [comment]
Andrew's idle sprites are now uploaded to my art folder under boss_sprites.

**Comment by goofanader** [comment]
![andrew_lee_front](https://cloud.githubusercontent.com/assets/799112/12857862/70c6aac8-cc01-11e5-9a33-ac14effec474.png) ![andrew_lee_idle](https://cloud.githubusercontent.com/assets/799112/12857863/70cab802-cc01-11e5-8b71-40e695780bdb.png) ![andrew_lee_idle_hand](https://cloud.githubusercontent.com/assets/799112/12857864/70cb64b4-cc01-11e5-8cdd-21e45084e793.png)

Andrew Lee's sprites. Artwork is done for Andrew, closing the issue.
