### ISSUE TITLE
Animation Code

### ISSUE THREAD

**Issue by adeeda** [goofanader/minna-no-fighting-game#26]
Once the sprite sheets are finalized, we gotta include all the animations.
- [x] Move player creation to the Character Select state.
- [x] Create animations based on the character's sprite sheet.
- [x] Update all calls to the animations, so that it's all right and good.

**Comment by adeeda** [comment]
I feel like what goofy has done is this, so I assigned her. She should mark this as done if it is indeed all done.

**Comment by goofanader** [comment]
This is indeed done, though it's not very smartly done...
